# Generated by Django 6.0.1 on 2026-01-16 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media_catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("owned", "Owned"),
                            ("watched", "Watched"),
                            ("read", "Read"),
                            ("listened", "Listened"),
                            ("wishlist", "Wishlist"),
                            ("borrowed", "Borrowed"),
                            ("lent", "Lent"),
                            ("in_progress", "In Progress"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Rating from 0.0 to 10.0",
                        max_digits=3,
                        null=True,
                        verbose_name="rating",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Private notes about this media",
                        verbose_name="notes",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="added at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user finished watching/reading/listening",
                        null=True,
                        verbose_name="completed at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_collections",
                        to="media_catalog.media",
                        verbose_name="media",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_collection",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user media",
                "verbose_name_plural": "user media",
                "db_table": "collections_usermedia",
                "ordering": ["-added_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="collections_user_id_06ec67_idx"
                    ),
                    models.Index(
                        fields=["media"], name="collections_media_i_f08ba3_idx"
                    ),
                    models.Index(
                        fields=["status"], name="collections_status_9e2dcb_idx"
                    ),
                    models.Index(
                        fields=["added_at"], name="collections_added_a_e261a3_idx"
                    ),
                    models.Index(
                        fields=["rating"], name="collections_rating_20b27b_idx"
                    ),
                ],
                "unique_together": {("user", "media", "status")},
            },
        ),
    ]
