# Generated by Django 6.0.1 on 2026-01-17 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
        ('media_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermedia',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='UserMediaCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Rating from 0.0 to 10.0', max_digits=3, null=True, verbose_name='rating')),
                ('notes', models.TextField(blank=True, help_text='Private notes about this media', verbose_name='notes')),
                ('is_owned', models.BooleanField(db_index=True, default=False, verbose_name='owned')),
                ('is_wishlist', models.BooleanField(db_index=True, default=False, verbose_name='in wishlist')),
                ('is_watched', models.BooleanField(db_index=True, default=False, verbose_name='watched/read/listened')),
                ('is_in_progress', models.BooleanField(db_index=True, default=False, verbose_name='in progress')),
                ('added_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='added to collection')),
                ('watched_at', models.DateTimeField(blank=True, help_text='When the user finished this media', null=True, verbose_name='watched/read/listened at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_collections', to='media_catalog.media', verbose_name='media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_collection', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user media collection',
                'verbose_name_plural': 'user media collections',
                'db_table': 'collections_usermedia_v2',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='LendingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lending_type', models.CharField(choices=[('lent', 'Lent to someone'), ('borrowed', 'Borrowed from someone')], max_length=10, verbose_name='lending type')),
                ('person_name', models.CharField(help_text='Who you lent to or borrowed from', max_length=200, verbose_name='person name')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('lent_at', models.DateTimeField(auto_now_add=True, verbose_name='lent/borrowed at')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='returned at')),
                ('is_returned', models.BooleanField(default=False, verbose_name='returned')),
                ('collection_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lending_records', to='collections.usermediacollection')),
            ],
            options={
                'verbose_name': 'lending record',
                'verbose_name_plural': 'lending records',
                'db_table': 'collections_lending_record',
                'ordering': ['-lent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usermediacollection',
            index=models.Index(fields=['user', 'is_owned'], name='collections_user_id_64f866_idx'),
        ),
        migrations.AddIndex(
            model_name='usermediacollection',
            index=models.Index(fields=['user', 'is_wishlist'], name='collections_user_id_1a27e4_idx'),
        ),
        migrations.AddIndex(
            model_name='usermediacollection',
            index=models.Index(fields=['user', 'is_watched'], name='collections_user_id_3a0ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='usermediacollection',
            index=models.Index(fields=['user', 'is_in_progress'], name='collections_user_id_3f0c1e_idx'),
        ),
        migrations.AddIndex(
            model_name='usermediacollection',
            index=models.Index(fields=['added_at'], name='collections_added_a_9932d9_idx'),
        ),
        migrations.AddIndex(
            model_name='usermediacollection',
            index=models.Index(fields=['rating'], name='collections_rating_70e742_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermediacollection',
            unique_together={('user', 'media')},
        ),
        migrations.AddIndex(
            model_name='lendingrecord',
            index=models.Index(fields=['collection_item', 'is_returned'], name='collections_collect_1d6862_idx'),
        ),
        migrations.AddIndex(
            model_name='lendingrecord',
            index=models.Index(fields=['lending_type'], name='collections_lending_feb43e_idx'),
        ),
    ]
