# Generated by Django 5.1 on 2026-01-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_collections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitem',
            name='status',
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='statuses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
