# Generated by Django 5.1 on 2026-01-27 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_collections', '0002_remove_collectionitem_status_collectionitem_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Allow anyone with the link to view this collection (read-only)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='share_token',
            field=models.CharField(blank=True, help_text='Unique token for shareable link', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Specific users who can view this collection', related_name='shared_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['share_token'], name='user_collec_share_t_7cfd5b_idx'),
        ),
    ]
