# Generated by Django 5.1 on 2026-01-25 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Geplant'), ('IN_PROGRESS', 'In Bearbeitung'), ('COMPLETED', 'Erledigt')], default='PLANNED', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_items', to='todos.todo')),
            ],
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', 'status'], name='todos_todo_user_id_c62cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', '-created_at'], name='todos_todo_user_id_da8bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['todo'], name='todos_todoi_todo_id_56e52b_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['content_type', 'object_id'], name='todos_todoi_content_e95170_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='todoitem',
            unique_together={('todo', 'content_type', 'object_id')},
        ),
    ]
