# Generated by Django 5.1 on 2026-01-25 17:40

import apps.documents.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=apps.documents.models.user_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'epub', 'mobi', 'txt', 'doc', 'docx'])])),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('EPUB', 'EPUB'), ('MOBI', 'MOBI'), ('TXT', 'Text'), ('DOC', 'Word Document'), ('DOCX', 'Word Document (DOCX)'), ('OTHER', 'Other')], max_length=10)),
                ('file_size', models.BigIntegerField()),
                ('authors', models.JSONField(blank=True, default=list)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='documents_d_user_id_a8f8c0_idx'), models.Index(fields=['title'], name='documents_d_title_ccf306_idx')],
            },
        ),
    ]
