# Generated by Django 5.1 on 2026-01-27 15:26

import apps.documents.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=apps.documents.models.user_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'epub', 'mobi', 'txt', 'md', 'markdown', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'odt', 'ods', 'odp'])]),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('EPUB', 'EPUB'), ('MOBI', 'MOBI'), ('TXT', 'Text'), ('MD', 'Markdown'), ('MARKDOWN', 'Markdown'), ('DOC', 'Word Document'), ('DOCX', 'Word Document (DOCX)'), ('XLS', 'Excel Spreadsheet'), ('XLSX', 'Excel Spreadsheet (XLSX)'), ('PPT', 'PowerPoint Presentation'), ('PPTX', 'PowerPoint Presentation (PPTX)'), ('ODT', 'OpenDocument Text'), ('ODS', 'OpenDocument Spreadsheet'), ('ODP', 'OpenDocument Presentation'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
