# Generated by Django 6.0.1 on 2026-01-16 18:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("tmdb", "TMDb"),
                            ("openlibrary", "Open Library"),
                            ("musicbrainz", "MusicBrainz"),
                        ],
                        max_length=50,
                        verbose_name="source",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="media type"
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last sync at"
                    ),
                ),
                (
                    "next_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="next sync at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "records_processed",
                    models.IntegerField(default=0, verbose_name="records processed"),
                ),
                (
                    "errors",
                    models.JSONField(blank=True, default=list, verbose_name="errors"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "sync task",
                "verbose_name_plural": "sync tasks",
                "db_table": "data_sync_synctask",
                "ordering": ["-created_at"],
            },
        ),
    ]
