# Generated by Django 5.1 on 2026-01-25 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('BOOK_ADDED', 'Buch zur Sammlung hinzugefügt'), ('BOOK_RATED', 'Buch bewertet'), ('DOCUMENT_UPLOADED', 'Dokument hochgeladen'), ('NOTE_CREATED', 'Notiz erstellt'), ('TODO_CREATED', 'Aufgabe erstellt'), ('TODO_COMPLETED', 'Aufgabe erledigt'), ('COLLECTION_CREATED', 'Sammlung erstellt'), ('STATUS_CHANGED', 'Status geändert')], max_length=30)),
                ('description', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='timeline_ac_user_id_b7ba5a_idx'), models.Index(fields=['activity_type', '-created_at'], name='timeline_ac_activit_49831b_idx')],
            },
        ),
    ]
