# Generated by Django 6.0.1 on 2026-01-16 18:29

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("movie", "Movie"),
                            ("tv_series", "TV Series"),
                            ("book", "Book"),
                            ("music", "Music"),
                            ("concert", "Concert"),
                            ("document", "Document"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="media type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=500, verbose_name="title"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="release date"
                    ),
                ),
                (
                    "cover_image_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="cover image URL"
                    ),
                ),
                (
                    "genres",
                    models.JSONField(blank=True, default=list, verbose_name="genres"),
                ),
                (
                    "external_ids",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="External API IDs (tmdb_id, imdb_id, isbn, etc.)",
                        verbose_name="external IDs",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-specific metadata",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="False for user-created private entries",
                        verbose_name="is public",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_media",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "media",
                "verbose_name_plural": "media",
                "db_table": "media_catalog_media",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "media_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media_catalog.media",
                    ),
                ),
                (
                    "authors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of book authors",
                        verbose_name="authors",
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="ISBN",
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="publisher"
                    ),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="page count"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="ISO 639-1 language code",
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                (
                    "openlibrary_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Open Library ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "book",
                "verbose_name_plural": "books",
                "db_table": "media_catalog_book",
            },
            bases=("media_catalog.media",),
        ),
        migrations.CreateModel(
            name="Concert",
            fields=[
                (
                    "media_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media_catalog.media",
                    ),
                ),
                ("artist", models.CharField(max_length=200, verbose_name="artist")),
                (
                    "venue",
                    models.CharField(blank=True, max_length=200, verbose_name="venue"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City, Country",
                        max_length=200,
                        verbose_name="location",
                    ),
                ),
                (
                    "event_date",
                    models.DateField(blank=True, null=True, verbose_name="event date"),
                ),
            ],
            options={
                "verbose_name": "concert",
                "verbose_name_plural": "concerts",
                "db_table": "media_catalog_concert",
            },
            bases=("media_catalog.media",),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "media_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media_catalog.media",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., article, paper, manual, guide",
                        max_length=100,
                        verbose_name="document type",
                    ),
                ),
                (
                    "author",
                    models.CharField(blank=True, max_length=200, verbose_name="author"),
                ),
                (
                    "file_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the document file",
                        max_length=500,
                        verbose_name="file URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documents",
                "db_table": "media_catalog_document",
            },
            bases=("media_catalog.media",),
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "media_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media_catalog.media",
                    ),
                ),
                (
                    "runtime_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="runtime (minutes)"
                    ),
                ),
                (
                    "director",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="director"
                    ),
                ),
                (
                    "cast",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of main cast members",
                        verbose_name="cast",
                    ),
                ),
                (
                    "tmdb_id",
                    models.IntegerField(
                        blank=True, null=True, unique=True, verbose_name="TMDb ID"
                    ),
                ),
                (
                    "imdb_id",
                    models.CharField(
                        blank=True, max_length=20, unique=True, verbose_name="IMDb ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "movie",
                "verbose_name_plural": "movies",
                "db_table": "media_catalog_movie",
            },
            bases=("media_catalog.media",),
        ),
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "media_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media_catalog.media",
                    ),
                ),
                (
                    "artists",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of artists",
                        verbose_name="artists",
                    ),
                ),
                (
                    "album_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("album", "Album"),
                            ("single", "Single"),
                            ("compilation", "Compilation"),
                            ("ep", "EP"),
                        ],
                        max_length=20,
                        verbose_name="album type",
                    ),
                ),
                (
                    "track_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="track count"
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="duration (seconds)"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="record label"
                    ),
                ),
                (
                    "musicbrainz_id",
                    models.UUIDField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="MusicBrainz ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "music",
                "verbose_name_plural": "music",
                "db_table": "media_catalog_music",
            },
            bases=("media_catalog.media",),
        ),
        migrations.CreateModel(
            name="TVSeries",
            fields=[
                (
                    "media_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media_catalog.media",
                    ),
                ),
                (
                    "number_of_seasons",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="number of seasons"
                    ),
                ),
                (
                    "number_of_episodes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="number of episodes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "creators",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of series creators",
                        verbose_name="creators",
                    ),
                ),
                (
                    "tmdb_id",
                    models.IntegerField(
                        blank=True, null=True, unique=True, verbose_name="TMDb ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "TV series",
                "verbose_name_plural": "TV series",
                "db_table": "media_catalog_tvseries",
            },
            bases=("media_catalog.media",),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(
                fields=["media_type"], name="media_catal_media_t_322046_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["title"], name="media_catal_title_91e8d0_idx"),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(
                fields=["release_date"], name="media_catal_release_99619b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(
                fields=["is_public"], name="media_catal_is_publ_a4549f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="media",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="media_catal_search__e02295_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="media",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["external_ids"], name="media_catal_externa_148a2e_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="media",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["genres"], name="media_catal_genres_efef42_gin"
            ),
        ),
    ]
